(prelude-require-packages '(color-theme-sanityinc-tomorrow
                           solarized-theme
                           auto-complete
                           ac-nrepl
                           nrepl-ritz
                           fold-dwim
                           icicles
                           js2-mode
                           evil
                           evil-nerd-commenter
                           evil-paredit
                           evil-leader
                           clojure-cheatsheet
                           graphene))
(prelude-require-packages
  '(
    ace-jump-mode
    auto-complete
    auto-complete-clang
    auto-dictionary
    buffer-move
    cc-mode
    color-moccur
    csharp-mode
    dash
    deft
    deferred
    diminish
    dired+
    elisp-slime-nav
    elixir-mix
    elixir-mode
    epc
    erc
    erlang
    evil
    evil-leader
    expand-region
    fill-column-indicator
    flycheck
    flycheck-color-mode-line
    fringe-helper
    fuzzy
    git-gutter-fringe
    ghc
    google-translate
    haskell-mode
    helm
    helm-c-yasnippet
    helm-projectile
    htmlize
    jedi
    less-css-mode
    magit
    markdown-mode
    move-text
    multi-term
    org
    org-bullets
    org-trello
    p4
    page-break-lines
    paredit
    popup
    popwin
    projectile
    puppet-mode
    python
    quickrun
    rainbow-mode
    rainbow-delimiters
    recentf
    rfringe
    ruby-end
    ruby-mode
    ruby-test-mode
    s
    smart-operator
    smartparens
    string-edit
    ;; stripe-buffer
    subword
    surround
    tagedit
    twittering-mode
    visual-regexp-steroids
    wdired
    yasnippet
    )  )

(package-initialize)

(provide 'packages-cs)
